name: Deploy to VM

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy code to VM
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/home/azureuser/app"

    - name: Deploy and run API on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo pkill node || true
          cd /home/azureuser/app
          npm install
          sudo nohup node index.js > app.log 2>&1 &
          sleep 3
          curl -f http://localhost/sayHello || (echo "API failed to start" && exit 1)
